import './globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-black">
        <div className="fixed inset-0 bg-gradient-to-b from-[#0d0d1a] to-[#1c1c2e] -z-10" />
        {children}
      </body>
    </html>
  )
}
